-- ===========================================================================
-- SBTF System — demonstration / development dataset (ANONYMISED)
-- Municipality of Mabini, Batangas — Franchising and Tricycle Driver
-- Registration System
--
-- !!! DEVELOPMENT ONLY !!!
-- This file creates synthetic accounts and records. It contains no real
-- personal information. Do NOT run it against the production project.
--
-- Applied automatically by:  supabase db reset
-- Applied manually by    :  psql "$DATABASE_URL" -f supabase/seed.sql
--
-- Generated by scripts/generate_seed.py — edit the generator, not the output.
-- ===========================================================================

begin;

-- ---------------------------------------------------------------------------
-- 0. Helper used to create Supabase Auth accounts with confirmed e-mail
--    addresses. Cryptography stays inside Supabase Auth (pgcrypto crypt()/
--    gen_salt()); the application never stores password material.
-- ---------------------------------------------------------------------------
create or replace function public.seed_create_auth_user(
  p_email      text,
  p_password   text,
  p_role       public.user_role,
  p_first_name text,
  p_middle_name text,
  p_last_name  text,
  p_contact    text,
  p_barangay   text,
  p_address    text,
  p_created_at timestamptz default now()
)
returns uuid
language plpgsql
security definer
set search_path = public, auth, extensions, pg_temp
as $$
declare
  v_id uuid := gen_random_uuid();
begin
  if exists (select 1 from public.profiles where lower(email) = lower(p_email)) then
    select id into v_id from public.profiles where lower(email) = lower(p_email);
    return v_id;
  end if;

  insert into auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
    confirmation_token, recovery_token, email_change_token_new, email_change
  )
  values (
    '00000000-0000-0000-0000-000000000000', v_id, 'authenticated', 'authenticated',
    lower(p_email), crypt(p_password, gen_salt('bf')), p_created_at,
    jsonb_build_object('provider', 'email', 'providers', array['email'], 'role', p_role),
    jsonb_build_object(
      'first_name', p_first_name, 'middle_name', p_middle_name, 'last_name', p_last_name,
      'contact_number', p_contact, 'address_line', p_address, 'barangay_code', p_barangay
    ),
    p_created_at, p_created_at, '', '', '', ''
  );

  if exists (
    select 1 from information_schema.columns
     where table_schema = 'auth' and table_name = 'identities' and column_name = 'provider_id'
  ) then
    execute $sql$
      insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
      values (gen_random_uuid(), $1, $2, jsonb_build_object('sub', $2, 'email', $3, 'email_verified', true), 'email', now(), now(), now())
    $sql$ using v_id, v_id::text, lower(p_email);
  else
    execute $sql$
      insert into auth.identities (id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
      values (gen_random_uuid(), $1, jsonb_build_object('sub', $1::text, 'email', $2, 'email_verified', true), 'email', now(), now(), now())
    $sql$ using v_id, lower(p_email);
  end if;

  -- The auth trigger has already created the profile row; complete it.
  update public.profiles
     set role = p_role,
         first_name = p_first_name,
         middle_name = nullif(btrim(coalesce(p_middle_name, '')), ''),
         last_name = p_last_name,
         contact_number = p_contact,
         address_line = p_address,
         barangay_code = p_barangay,
         account_status = 'active',
         created_at = p_created_at
   where id = v_id;

  return v_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 1. TODAs (24 accredited associations)
-- ---------------------------------------------------------------------------
insert into public.todas (code, name, barangay_code, zone) values
  ('TODA-001', 'TODA Anilao Proper', '041016001', 'Zone 1'),
  ('TODA-002', 'TODA Anilao East', '041016002', 'Zone 2'),
  ('TODA-003', 'TODA Bagalangit', '041016003', 'Zone 3'),
  ('TODA-004', 'TODA Bulacan', '041016004', 'Zone 4'),
  ('TODA-005', 'TODA Calamias', '041016005', 'Zone 5'),
  ('TODA-006', 'TODA Estrella', '041016006', 'Zone 6'),
  ('TODA-007', 'TODA Gasang', '041016007', 'Zone 1'),
  ('TODA-008', 'TODA Laurel', '041016008', 'Zone 2'),
  ('TODA-009', 'TODA Ligaya', '041016009', 'Zone 3'),
  ('TODA-010', 'TODA Mainaga', '041016010', 'Zone 4'),
  ('TODA-011', 'TODA Mainit', '041016011', 'Zone 5'),
  ('TODA-012', 'TODA Majuben', '041016012', 'Zone 6'),
  ('TODA-013', 'TODA Malimatoc', '041016013', 'Zone 1'),
  ('TODA-014', 'TODA Nag-iba', '041016015', 'Zone 2'),
  ('TODA-015', 'TODA Pilahan', '041016016', 'Zone 3'),
  ('TODA-016', 'TODA Poblacion', '041016017', 'Zone 4'),
  ('TODA-017', 'TODA Pulang Lupa', '041016018', 'Zone 5'),
  ('TODA-018', 'TODA Pulong Anahao', '041016019', 'Zone 6'),
  ('TODA-019', 'TODA Pulong Niogan', '041016021', 'Zone 1'),
  ('TODA-020', 'TODA Saguing', '041016022', 'Zone 2'),
  ('TODA-021', 'TODA Sampaguita', '041016023', 'Zone 3'),
  ('TODA-022', 'TODA San Francisco', '041016024', 'Zone 4'),
  ('TODA-023', 'TODA San Teodoro', '041016027', 'Zone 5'),
  ('TODA-024', 'TODA Talaga', '041016034', 'Zone 6')
on conflict (code) do nothing;

-- ---------------------------------------------------------------------------
-- 2. TODA membership masterlist — 817 anonymised members
--    No names, addresses or contact details: membership statistics only.
-- ---------------------------------------------------------------------------
with counts as (
  select * from (values
    ('TODA-001', 63),
    ('TODA-002', 57),
    ('TODA-003', 54),
    ('TODA-004', 50),
    ('TODA-005', 46),
    ('TODA-006', 43),
    ('TODA-007', 41),
    ('TODA-008', 39),
    ('TODA-009', 37),
    ('TODA-010', 35),
    ('TODA-011', 33),
    ('TODA-012', 31),
    ('TODA-013', 30),
    ('TODA-014', 28),
    ('TODA-015', 28),
    ('TODA-016', 26),
    ('TODA-017', 26),
    ('TODA-018', 24),
    ('TODA-019', 24),
    ('TODA-020', 22),
    ('TODA-021', 22),
    ('TODA-022', 20),
    ('TODA-023', 20),
    ('TODA-024', 18)
  ) as t(code, member_count)
)
insert into public.toda_members (toda_id, member_ref, display_name, year_joined, is_active)
select t.id,
       t.code || '-M' || lpad(gs.n::text, 4, '0'),
       'Member ' || lpad(gs.n::text, 4, '0'),
       -- Deterministic spread of join years between 1998 and 2025
       (1998 + ((gs.n * 7 + length(t.code)) % 28))::smallint,
       (gs.n % 17 <> 0)  -- roughly 6% inactive roster entries
  from counts c
  join public.todas t on t.code = c.code
  cross join lateral generate_series(1, c.member_count) as gs(n)
on conflict (member_ref) do nothing;

-- ---------------------------------------------------------------------------
-- 3. Demonstration accounts
--    administrator : 1 account
--    staff         : 3 accounts
--    driver        : 72 accounts (three per TODA, linked to the roster)
--    Passwords are demonstration values and must be changed in any real
--    deployment (they are documented in docs/deployment.md).
-- ---------------------------------------------------------------------------
do $$
declare
  v_id uuid;
  r    record;
begin
  perform public.seed_create_auth_user(
    'admin@mabini-sbtf.test', 'Admin@Mabini2026', 'administrator',
    'Apolinaria', 'Reyes', 'Domingo', '09171234501', '041016017',
    'Municipal Hall, Poblacion, Mabini, Batangas', now() - interval '400 days');

  perform public.seed_create_auth_user(
    'staff1@mabini-sbtf.test', 'Staff@Mabini2026', 'staff',
    'Benigno', 'Cruz', 'Magsaysay', '09171234502', '041016017',
    'Sangguniang Bayan Office, Poblacion, Mabini, Batangas', now() - interval '380 days');

  perform public.seed_create_auth_user(
    'staff2@mabini-sbtf.test', 'Staff@Mabini2026', 'staff',
    'Corazon', 'Lim', 'Villamor', '09171234503', '041016017',
    'Sangguniang Bayan Office, Poblacion, Mabini, Batangas', now() - interval '300 days');

  perform public.seed_create_auth_user(
    'staff3@mabini-sbtf.test', 'Staff@Mabini2026', 'staff',
    'Diosdado', 'Ybañez', 'Panganiban', '09171234504', '041016009',
    'Sangguniang Bayan Office, Poblacion, Mabini, Batangas', now() - interval '120 days');

  -- Driver accounts: two to three per TODA so every dashboard segment has data.
  for r in
    select t.code, t.barangay_code, row_number() over (order by t.code) as toda_rank
      from public.todas t
  loop
    for i in 1..3 loop
      v_id := public.seed_create_auth_user(
        'driver' || lpad((r.toda_rank * 10 + i)::text, 3, '0') || '@mabini-sbtf.test',
        'Driver@Mabini2026', 'driver',
        (array['Adrian','Alvin','Arnel','Benjamin','Carlito','Danilo','Dennis','Edgar','Efren','Elmer','Ernesto','Ferdinand','Gilbert','Gregorio','Henry','Isagani','Jaime','Joel','Jonathan','Jose','Julio','Leonardo','Lorenzo','Manuel','Marcelo','Mario','Marvin','Melchor','Michael','Nestor','Noel','Oliver','Orlando','Oscar','Pablo','Pedro','Rafael','Ramil','Ramon','Raul','Renato','Ricardo','Roberto','Rodolfo','Rogelio','Rolando','Romeo','Ronald','Ruben','Salvador','Samuel','Teodoro','Vincent','Virgilio','Wilfredo','Wilson','Antonio','Cesar','Dominador','Emmanuel'])[(r.toda_rank * 3 + i) % 60 + 1],
        (array['Abad','Aguilar','Alcantara','Alvarez','Angeles','Aquino','Bautista','Bernardo','Cabrera','Castro','Cortez','Cruz','Diaz','Domingo','Enriquez','Espino','Estrada','Fernandez','Flores','Francisco','Garcia','Gonzales','Hernandez','Jimenez','Lopez','Mendoza','Mercado','Navarro','Ocampo','Ortiz','Padilla','Pascual','Perez','Ramos','Reyes','Rivera','Rodriguez','Rosales','Salazar','Santiago','Santos','Tolentino','Torres','Valdez','Villanueva','Zamora','Marasigan','Manalo','Malabanan','Macatangay'])[(r.toda_rank * 3 + i) % 50 + 1],
        (array['Abanto','Agbayani','Almario','Atienza','Balbuena','Banaag','Bautista','Briones','Buenaventura','Cabrera','Cantos','Claveria','Contreras','Dalisay','De Guzman','Dimaculangan','Dimaano','Ebora','Fajardo','Feliciano','Garcia','Gonzales','Guevarra','Hernandez','Javier','Landicho','Lipa','Malabanan','Mendoza','Miranda','Nolasco','Ocampo','Olivares','Ortega','Panganiban','Pastor','Perez','Quinto','Ramos','Ramoso','Rico','Rivera','Salazar','Sandoval','Sarmiento','Silang','Sison','Tenorio','Tolentino','Umali','Valencia','Vasquez','Villamor','Yabut','Zamora'])[(r.toda_rank * 3 + i) % 55 + 1],
        '0918' || lpad(((r.toda_rank * 37 + i * 7) % 10000000)::text, 7, '0'),
        r.barangay_code,
        'Purok ' || (1 + (r.toda_rank % 5)) || ', ' || r.code,
        now() - ((r.toda_rank * 3 + i) * 7 + 20) * interval '1 day');
    end loop;
  end loop;

  -- Link roster entries to the registered accounts of their TODA.
  with ranked as (
    select m.id,
           row_number() over (partition by m.toda_id order by m.member_ref) as rn
      from public.toda_members m
  )
  update public.toda_members m
     set profile_id = d.id
    from ranked r
    join public.profiles d
      on d.role = 'driver'
     and d.toda_id = (select toda_id from public.toda_members where id = r.id)
     and d.email like 'driver%'
   where m.id = r.id and r.rn <= 3;
end
$$;

-- ---------------------------------------------------------------------------
-- 4. Demonstration applications (180 records: 123 new / 57 renewals),
--    the four documentary requirements of each, and the franchise records
--    issued on approval.
--    Submitted over a two-year window with a seasonal renewal peak so that the
--    descriptive analytics have a realistic shape. Renewals reference the
--    franchise record of the driver's earlier approved application.
-- ---------------------------------------------------------------------------
create temporary table seed_apps (
  ordinal          integer primary key,
  driver_email     text not null,
  toda_code        text not null,
  application_type public.application_type not null,
  status           public.application_status not null,
  submitted_at     timestamptz not null,
  reviewed_at      timestamptz,
  plate_number     text not null,
  vehicle_make     text not null,
  vehicle_model    text not null,
  vehicle_year     smallint not null,
  vehicle_color    text not null,
  engine_number    text not null,
  chassis_number   text not null,
  seating_capacity smallint not null,
  predecessor_seq  integer
) on commit drop;

insert into seed_apps (ordinal, driver_email, toda_code, application_type, status, submitted_at, reviewed_at, plate_number, vehicle_make, vehicle_model, vehicle_year, vehicle_color, engine_number, chassis_number, seating_capacity, predecessor_seq) values
  (0, 'driver011@mabini-sbtf.test', 'TODA-001', 'new', 'pending', '2024-01-01T09:00:00+00:00', null, 'TRI 1007', 'Kawasaki', 'Barako 175', 2006, 'Red', 'ENG00000131', 'CHS00000197', 5, null),
  (1, 'driver143@mabini-sbtf.test', 'TODA-014', 'new', 'approved', '2024-01-09T09:00:00+00:00', '2024-01-19T14:30:00+00:00', 'TRI 1294', 'Yamaha', 'YBR 125', 2009, 'Black', 'ENG00005502', 'CHS00008274', 4, null),
  (2, 'driver071@mabini-sbtf.test', 'TODA-007', 'new', 'pending', '2024-01-19T09:00:00+00:00', null, 'TRI 1133', 'Honda', 'XRM 125', 2005, 'Gray', 'ENG00002489', 'CHS00003743', 5, null),
  (3, 'driver222@mabini-sbtf.test', 'TODA-022', 'new', 'rejected', '2024-01-26T09:00:00+00:00', '2024-01-27T14:30:00+00:00', 'TRI 1455', 'Honda', 'Wave 125', 2013, 'Green', 'ENG00008515', 'CHS00012805', 6, null),
  (4, 'driver133@mabini-sbtf.test', 'TODA-013', 'new', 'approved', '2024-02-06T09:00:00+00:00', '2024-02-13T14:30:00+00:00', 'TRI 1273', 'Honda', 'XRM 125', 2006, 'Gray', 'ENG00005109', 'CHS00007683', 4, null),
  (5, 'driver061@mabini-sbtf.test', 'TODA-006', 'new', 'approved', '2024-02-16T09:00:00+00:00', '2024-02-20T14:30:00+00:00', 'TRI 1112', 'Rusi', 'Classic 250', 2021, 'Yellow', 'ENG00002096', 'CHS00003152', 5, null),
  (6, 'driver051@mabini-sbtf.test', 'TODA-005', 'new', 'pending', '2024-03-13T09:00:00+00:00', null, 'TRI 1091', 'Suzuki', 'GD 110', 2018, 'White', 'ENG00001703', 'CHS00002561', 5, null),
  (7, 'driver212@mabini-sbtf.test', 'TODA-021', 'new', 'approved', '2024-03-23T09:00:00+00:00', '2024-04-02T14:30:00+00:00', 'TRI 1434', 'Yamaha', 'YBR 125', 2010, 'Black', 'ENG00008122', 'CHS00012214', 6, null),
  (8, 'driver123@mabini-sbtf.test', 'TODA-012', 'new', 'approved', '2024-04-03T09:00:00+00:00', '2024-04-07T14:30:00+00:00', 'TRI 1252', 'Rusi', 'Classic 250', 2022, 'Yellow', 'ENG00004716', 'CHS00007092', 4, null),
  (9, 'driver202@mabini-sbtf.test', 'TODA-020', 'new', 'approved', '2024-05-20T09:00:00+00:00', '2024-05-27T14:30:00+00:00', 'TRI 1413', 'Honda', 'XRM 125', 2007, 'Gray', 'ENG00007729', 'CHS00011623', 6, null),
  (10, 'driver041@mabini-sbtf.test', 'TODA-004', 'new', 'approved', '2024-06-10T09:00:00+00:00', '2024-06-20T14:30:00+00:00', 'TRI 1070', 'Honda', 'TMX 155', 2015, 'Blue', 'ENG00001310', 'CHS00001970', 5, null),
  (11, 'driver071@mabini-sbtf.test', 'TODA-007', 'new', 'pending', '2025-01-01T09:00:00+00:00', null, 'TRI 1133', 'Honda', 'XRM 125', 2005, 'Gray', 'ENG00002489', 'CHS00003743', 5, null),
  (12, 'driver131@mabini-sbtf.test', 'TODA-013', 'new', 'pending', '2025-01-01T09:00:00+00:00', null, 'TRI 1259', 'Motorstar', 'Z200', 2023, 'Maroon', 'ENG00004847', 'CHS00007289', 5, null),
  (13, 'driver191@mabini-sbtf.test', 'TODA-019', 'new', 'pending', '2025-01-01T09:00:00+00:00', null, 'TRI 1385', 'Honda', 'Wave 125', 2022, 'Green', 'ENG00007205', 'CHS00010835', 5, null),
  (14, 'driver222@mabini-sbtf.test', 'TODA-022', 'new', 'rejected', '2025-01-08T09:00:00+00:00', '2025-01-09T14:30:00+00:00', 'TRI 1455', 'Honda', 'Wave 125', 2013, 'Green', 'ENG00008515', 'CHS00012805', 6, null),
  (15, 'driver042@mabini-sbtf.test', 'TODA-004', 'new', 'rejected', '2025-01-08T09:00:00+00:00', '2025-01-15T14:30:00+00:00', 'TRI 1077', 'Kawasaki', 'Barako 175', 2016, 'Red', 'ENG00001441', 'CHS00002167', 6, null),
  (16, 'driver102@mabini-sbtf.test', 'TODA-010', 'new', 'rejected', '2025-01-08T09:00:00+00:00', '2025-01-09T14:30:00+00:00', 'TRI 1203', 'Honda', 'XRM 125', 2015, 'Gray', 'ENG00003799', 'CHS00005713', 6, null),
  (17, 'driver023@mabini-sbtf.test', 'TODA-002', 'new', 'approved', '2025-01-09T09:00:00+00:00', '2025-01-19T14:30:00+00:00', 'TRI 1042', 'Rusi', 'Classic 250', 2011, 'Yellow', 'ENG00000786', 'CHS00001182', 4, null),
  (18, 'driver083@mabini-sbtf.test', 'TODA-008', 'new', 'approved', '2025-01-09T09:00:00+00:00', '2025-01-13T14:30:00+00:00', 'TRI 1168', 'Kawasaki', 'CT100', 2010, 'Silver', 'ENG00003144', 'CHS00004728', 4, null),
  (19, 'driver203@mabini-sbtf.test', 'TODA-020', 'new', 'approved', '2025-01-09T09:00:00+00:00', '2025-01-13T14:30:00+00:00', 'TRI 1420', 'Honda', 'TMX 155', 2008, 'Blue', 'ENG00007860', 'CHS00011820', 4, null),
  (20, 'driver131@mabini-sbtf.test', 'TODA-013', 'new', 'pending', '2025-01-10T09:00:00+00:00', null, 'TRI 1259', 'Motorstar', 'Z200', 2023, 'Maroon', 'ENG00004847', 'CHS00007289', 5, null),
  (21, 'driver191@mabini-sbtf.test', 'TODA-019', 'new', 'pending', '2025-01-10T09:00:00+00:00', null, 'TRI 1385', 'Honda', 'Wave 125', 2022, 'Green', 'ENG00007205', 'CHS00010835', 5, null),
  (22, 'driver011@mabini-sbtf.test', 'TODA-001', 'new', 'pending', '2025-01-10T09:00:00+00:00', null, 'TRI 1007', 'Kawasaki', 'Barako 175', 2006, 'Red', 'ENG00000131', 'CHS00000197', 5, null),
  (23, 'driver042@mabini-sbtf.test', 'TODA-004', 'new', 'rejected', '2025-01-17T09:00:00+00:00', '2025-01-24T14:30:00+00:00', 'TRI 1077', 'Kawasaki', 'Barako 175', 2016, 'Red', 'ENG00001441', 'CHS00002167', 6, null),
  (24, 'driver102@mabini-sbtf.test', 'TODA-010', 'new', 'rejected', '2025-01-17T09:00:00+00:00', '2025-01-18T14:30:00+00:00', 'TRI 1203', 'Honda', 'XRM 125', 2015, 'Gray', 'ENG00003799', 'CHS00005713', 6, null),
  (25, 'driver162@mabini-sbtf.test', 'TODA-016', 'new', 'rejected', '2025-01-17T09:00:00+00:00', '2025-01-24T14:30:00+00:00', 'TRI 1329', 'Motorstar', 'Z200', 2014, 'Maroon', 'ENG00006157', 'CHS00009259', 6, null),
  (26, 'driver143@mabini-sbtf.test', 'TODA-014', 'renewal', 'approved', '2025-01-18T09:00:00+00:00', '2025-01-28T14:30:00+00:00', 'TRI 1294', 'Yamaha', 'YBR 125', 2009, 'Black', 'ENG00005502', 'CHS00008274', 4, 1),
  (27, 'driver203@mabini-sbtf.test', 'TODA-020', 'renewal', 'approved', '2025-01-18T09:00:00+00:00', '2025-01-22T14:30:00+00:00', 'TRI 1420', 'Honda', 'TMX 155', 2008, 'Blue', 'ENG00007860', 'CHS00011820', 4, 19),
  (28, 'driver023@mabini-sbtf.test', 'TODA-002', 'renewal', 'approved', '2025-01-18T09:00:00+00:00', '2025-01-28T14:30:00+00:00', 'TRI 1042', 'Rusi', 'Classic 250', 2011, 'Yellow', 'ENG00000786', 'CHS00001182', 4, 17),
  (29, 'driver191@mabini-sbtf.test', 'TODA-019', 'new', 'pending', '2025-01-19T09:00:00+00:00', null, 'TRI 1385', 'Honda', 'Wave 125', 2022, 'Green', 'ENG00007205', 'CHS00010835', 5, null),
  (30, 'driver011@mabini-sbtf.test', 'TODA-001', 'new', 'pending', '2025-01-19T09:00:00+00:00', null, 'TRI 1007', 'Kawasaki', 'Barako 175', 2006, 'Red', 'ENG00000131', 'CHS00000197', 5, null),
  (31, 'driver102@mabini-sbtf.test', 'TODA-010', 'new', 'rejected', '2025-01-26T09:00:00+00:00', '2025-01-27T14:30:00+00:00', 'TRI 1203', 'Honda', 'XRM 125', 2015, 'Gray', 'ENG00003799', 'CHS00005713', 6, null),
  (32, 'driver162@mabini-sbtf.test', 'TODA-016', 'new', 'rejected', '2025-01-26T09:00:00+00:00', '2025-02-02T14:30:00+00:00', 'TRI 1329', 'Motorstar', 'Z200', 2014, 'Maroon', 'ENG00006157', 'CHS00009259', 6, null),
  (33, 'driver042@mabini-sbtf.test', 'TODA-004', 'new', 'rejected', '2025-01-26T09:00:00+00:00', '2025-02-02T14:30:00+00:00', 'TRI 1077', 'Kawasaki', 'Barako 175', 2016, 'Red', 'ENG00001441', 'CHS00002167', 6, null),
  (34, 'driver203@mabini-sbtf.test', 'TODA-020', 'renewal', 'approved', '2025-01-27T09:00:00+00:00', '2025-01-31T14:30:00+00:00', 'TRI 1420', 'Honda', 'TMX 155', 2008, 'Blue', 'ENG00007860', 'CHS00011820', 4, 27),
  (35, 'driver023@mabini-sbtf.test', 'TODA-002', 'renewal', 'approved', '2025-01-27T09:00:00+00:00', '2025-02-06T14:30:00+00:00', 'TRI 1042', 'Rusi', 'Classic 250', 2011, 'Yellow', 'ENG00000786', 'CHS00001182', 4, 28),
  (36, 'driver083@mabini-sbtf.test', 'TODA-008', 'renewal', 'approved', '2025-01-27T09:00:00+00:00', '2025-01-31T14:30:00+00:00', 'TRI 1168', 'Kawasaki', 'CT100', 2010, 'Silver', 'ENG00003144', 'CHS00004728', 4, 18),
  (37, 'driver073@mabini-sbtf.test', 'TODA-007', 'new', 'approved', '2025-02-06T09:00:00+00:00', '2025-02-07T14:30:00+00:00', 'TRI 1147', 'Kawasaki', 'Barako 175', 2007, 'Red', 'ENG00002751', 'CHS00004137', 4, null),
  (38, 'driver193@mabini-sbtf.test', 'TODA-019', 'new', 'approved', '2025-02-06T09:00:00+00:00', '2025-02-07T14:30:00+00:00', 'TRI 1399', 'Motorstar', 'Z200', 2005, 'Maroon', 'ENG00007467', 'CHS00011229', 4, null),
  (39, 'driver121@mabini-sbtf.test', 'TODA-012', 'new', 'approved', '2025-02-07T09:00:00+00:00', '2025-02-17T14:30:00+00:00', 'TRI 1238', 'Kawasaki', 'CT100', 2020, 'Silver', 'ENG00004454', 'CHS00006698', 5, null),
  (40, 'driver181@mabini-sbtf.test', 'TODA-018', 'new', 'approved', '2025-02-07T09:00:00+00:00', '2025-02-11T14:30:00+00:00', 'TRI 1364', 'Yamaha', 'YBR 125', 2019, 'Black', 'ENG00006812', 'CHS00010244', 5, null),
  (41, 'driver241@mabini-sbtf.test', 'TODA-024', 'new', 'approved', '2025-02-07T09:00:00+00:00', '2025-02-17T14:30:00+00:00', 'TRI 1490', 'Honda', 'TMX 155', 2018, 'Blue', 'ENG00009170', 'CHS00013790', 5, null),
  (42, 'driver061@mabini-sbtf.test', 'TODA-006', 'new', 'approved', '2025-02-07T09:00:00+00:00', '2025-02-11T14:30:00+00:00', 'TRI 1112', 'Rusi', 'Classic 250', 2021, 'Yellow', 'ENG00002096', 'CHS00003152', 5, null),
  (43, 'driver133@mabini-sbtf.test', 'TODA-013', 'renewal', 'approved', '2025-02-15T09:00:00+00:00', '2025-02-22T14:30:00+00:00', 'TRI 1273', 'Honda', 'XRM 125', 2006, 'Gray', 'ENG00005109', 'CHS00007683', 4, 4),
  (44, 'driver193@mabini-sbtf.test', 'TODA-019', 'renewal', 'approved', '2025-02-15T09:00:00+00:00', '2025-02-16T14:30:00+00:00', 'TRI 1399', 'Motorstar', 'Z200', 2005, 'Maroon', 'ENG00007467', 'CHS00011229', 4, 38),
  (45, 'driver013@mabini-sbtf.test', 'TODA-001', 'new', 'approved', '2025-02-15T09:00:00+00:00', '2025-02-22T14:30:00+00:00', 'TRI 1021', 'Suzuki', 'GD 110', 2008, 'White', 'ENG00000393', 'CHS00000591', 4, null),
  (46, 'driver241@mabini-sbtf.test', 'TODA-024', 'new', 'approved', '2025-02-16T09:00:00+00:00', '2025-02-26T14:30:00+00:00', 'TRI 1490', 'Honda', 'TMX 155', 2018, 'Blue', 'ENG00009170', 'CHS00013790', 5, null),
  (47, 'driver121@mabini-sbtf.test', 'TODA-012', 'new', 'approved', '2025-02-16T09:00:00+00:00', '2025-02-26T14:30:00+00:00', 'TRI 1238', 'Kawasaki', 'CT100', 2020, 'Silver', 'ENG00004454', 'CHS00006698', 5, null),
  (48, 'driver193@mabini-sbtf.test', 'TODA-019', 'renewal', 'approved', '2025-02-24T09:00:00+00:00', '2025-02-25T14:30:00+00:00', 'TRI 1399', 'Motorstar', 'Z200', 2005, 'Maroon', 'ENG00007467', 'CHS00011229', 4, 44),
  (49, 'driver013@mabini-sbtf.test', 'TODA-001', 'renewal', 'approved', '2025-02-24T09:00:00+00:00', '2025-03-03T14:30:00+00:00', 'TRI 1021', 'Suzuki', 'GD 110', 2008, 'White', 'ENG00000393', 'CHS00000591', 4, 45),
  (50, 'driver073@mabini-sbtf.test', 'TODA-007', 'renewal', 'approved', '2025-02-24T09:00:00+00:00', '2025-02-25T14:30:00+00:00', 'TRI 1147', 'Kawasaki', 'Barako 175', 2007, 'Red', 'ENG00002751', 'CHS00004137', 4, 37),
  (51, 'driver133@mabini-sbtf.test', 'TODA-013', 'renewal', 'approved', '2025-02-24T09:00:00+00:00', '2025-03-03T14:30:00+00:00', 'TRI 1273', 'Honda', 'XRM 125', 2006, 'Gray', 'ENG00005109', 'CHS00007683', 4, 43),
  (52, 'driver061@mabini-sbtf.test', 'TODA-006', 'new', 'approved', '2025-02-25T09:00:00+00:00', '2025-03-01T14:30:00+00:00', 'TRI 1112', 'Rusi', 'Classic 250', 2021, 'Yellow', 'ENG00002096', 'CHS00003152', 5, null),
  (53, 'driver121@mabini-sbtf.test', 'TODA-012', 'new', 'approved', '2025-02-25T09:00:00+00:00', '2025-03-07T14:30:00+00:00', 'TRI 1238', 'Kawasaki', 'CT100', 2020, 'Silver', 'ENG00004454', 'CHS00006698', 5, null),
  (54, 'driver181@mabini-sbtf.test', 'TODA-018', 'new', 'approved', '2025-02-25T09:00:00+00:00', '2025-03-01T14:30:00+00:00', 'TRI 1364', 'Yamaha', 'YBR 125', 2019, 'Black', 'ENG00006812', 'CHS00010244', 5, null),
  (55, 'driver171@mabini-sbtf.test', 'TODA-017', 'new', 'pending', '2025-03-04T09:00:00+00:00', null, 'TRI 1343', 'Honda', 'XRM 125', 2016, 'Gray', 'ENG00006419', 'CHS00009653', 5, null),
  (56, 'driver231@mabini-sbtf.test', 'TODA-023', 'new', 'pending', '2025-03-04T09:00:00+00:00', null, 'TRI 1469', 'Motorstar', 'Z200', 2015, 'Maroon', 'ENG00008777', 'CHS00013199', 5, null),
  (57, 'driver051@mabini-sbtf.test', 'TODA-005', 'new', 'pending', '2025-03-04T09:00:00+00:00', null, 'TRI 1091', 'Suzuki', 'GD 110', 2018, 'White', 'ENG00001703', 'CHS00002561', 5, null),
  (58, 'driver212@mabini-sbtf.test', 'TODA-021', 'renewal', 'approved', '2025-03-05T09:00:00+00:00', '2025-03-15T14:30:00+00:00', 'TRI 1434', 'Yamaha', 'YBR 125', 2010, 'Black', 'ENG00008122', 'CHS00012214', 6, 7),
  (59, 'driver032@mabini-sbtf.test', 'TODA-003', 'new', 'approved', '2025-03-05T09:00:00+00:00', '2025-03-09T14:30:00+00:00', 'TRI 1056', 'Kawasaki', 'Curve 110', 2013, 'Orange', 'ENG00001048', 'CHS00001576', 6, null),
  (60, 'driver092@mabini-sbtf.test', 'TODA-009', 'new', 'approved', '2025-03-05T09:00:00+00:00', '2025-03-15T14:30:00+00:00', 'TRI 1182', 'Rusi', 'Classic 250', 2012, 'Yellow', 'ENG00003406', 'CHS00005122', 6, null),
  (61, 'driver231@mabini-sbtf.test', 'TODA-023', 'new', 'pending', '2025-03-13T09:00:00+00:00', null, 'TRI 1469', 'Motorstar', 'Z200', 2015, 'Maroon', 'ENG00008777', 'CHS00013199', 5, null),
  (62, 'driver111@mabini-sbtf.test', 'TODA-011', 'new', 'pending', '2025-03-13T09:00:00+00:00', null, 'TRI 1217', 'Kawasaki', 'Barako 175', 2017, 'Red', 'ENG00004061', 'CHS00006107', 5, null),
  (63, 'driver032@mabini-sbtf.test', 'TODA-003', 'renewal', 'approved', '2025-03-14T09:00:00+00:00', '2025-03-18T14:30:00+00:00', 'TRI 1056', 'Kawasaki', 'Curve 110', 2013, 'Orange', 'ENG00001048', 'CHS00001576', 6, 59),
  (64, 'driver092@mabini-sbtf.test', 'TODA-009', 'renewal', 'approved', '2025-03-14T09:00:00+00:00', '2025-03-24T14:30:00+00:00', 'TRI 1182', 'Rusi', 'Classic 250', 2012, 'Yellow', 'ENG00003406', 'CHS00005122', 6, 60),
  (65, 'driver152@mabini-sbtf.test', 'TODA-015', 'new', 'approved', '2025-03-14T09:00:00+00:00', '2025-03-18T14:30:00+00:00', 'TRI 1308', 'Kawasaki', 'CT100', 2011, 'Silver', 'ENG00005764', 'CHS00008668', 6, null),
  (66, 'driver212@mabini-sbtf.test', 'TODA-021', 'renewal', 'approved', '2025-03-14T09:00:00+00:00', '2025-03-24T14:30:00+00:00', 'TRI 1434', 'Yamaha', 'YBR 125', 2010, 'Black', 'ENG00008122', 'CHS00012214', 6, 58),
  (67, 'driver051@mabini-sbtf.test', 'TODA-005', 'new', 'pending', '2025-03-22T09:00:00+00:00', null, 'TRI 1091', 'Suzuki', 'GD 110', 2018, 'White', 'ENG00001703', 'CHS00002561', 5, null),
  (68, 'driver111@mabini-sbtf.test', 'TODA-011', 'new', 'pending', '2025-03-22T09:00:00+00:00', null, 'TRI 1217', 'Kawasaki', 'Barako 175', 2017, 'Red', 'ENG00004061', 'CHS00006107', 5, null),
  (69, 'driver171@mabini-sbtf.test', 'TODA-017', 'new', 'pending', '2025-03-22T09:00:00+00:00', null, 'TRI 1343', 'Honda', 'XRM 125', 2016, 'Gray', 'ENG00006419', 'CHS00009653', 5, null),
  (70, 'driver231@mabini-sbtf.test', 'TODA-023', 'new', 'pending', '2025-03-22T09:00:00+00:00', null, 'TRI 1469', 'Motorstar', 'Z200', 2015, 'Maroon', 'ENG00008777', 'CHS00013199', 5, null),
  (71, 'driver152@mabini-sbtf.test', 'TODA-015', 'renewal', 'approved', '2025-03-23T09:00:00+00:00', '2025-03-27T14:30:00+00:00', 'TRI 1308', 'Kawasaki', 'CT100', 2011, 'Silver', 'ENG00005764', 'CHS00008668', 6, 65),
  (72, 'driver032@mabini-sbtf.test', 'TODA-003', 'renewal', 'approved', '2025-03-23T09:00:00+00:00', '2025-03-27T14:30:00+00:00', 'TRI 1056', 'Kawasaki', 'Curve 110', 2013, 'Orange', 'ENG00001048', 'CHS00001576', 6, 63),
  (73, 'driver063@mabini-sbtf.test', 'TODA-006', 'new', 'approved', '2025-04-03T09:00:00+00:00', '2025-04-13T14:30:00+00:00', 'TRI 1126', 'Kawasaki', 'Curve 110', 2023, 'Orange', 'ENG00002358', 'CHS00003546', 4, null),
  (74, 'driver183@mabini-sbtf.test', 'TODA-018', 'new', 'approved', '2025-04-03T09:00:00+00:00', '2025-04-13T14:30:00+00:00', 'TRI 1378', 'Kawasaki', 'CT100', 2021, 'Silver', 'ENG00007074', 'CHS00010638', 4, null),
  (75, 'driver123@mabini-sbtf.test', 'TODA-012', 'renewal', 'approved', '2025-04-12T09:00:00+00:00', '2025-04-16T14:30:00+00:00', 'TRI 1252', 'Rusi', 'Classic 250', 2022, 'Yellow', 'ENG00004716', 'CHS00007092', 4, 8),
  (76, 'driver183@mabini-sbtf.test', 'TODA-018', 'renewal', 'approved', '2025-04-12T09:00:00+00:00', '2025-04-22T14:30:00+00:00', 'TRI 1378', 'Kawasaki', 'CT100', 2021, 'Silver', 'ENG00007074', 'CHS00010638', 4, 74),
  (77, 'driver243@mabini-sbtf.test', 'TODA-024', 'new', 'approved', '2025-04-12T09:00:00+00:00', '2025-04-16T14:30:00+00:00', 'TRI 1504', 'Yamaha', 'YBR 125', 2020, 'Black', 'ENG00009432', 'CHS00014184', 4, null),
  (78, 'driver063@mabini-sbtf.test', 'TODA-006', 'renewal', 'approved', '2025-04-12T09:00:00+00:00', '2025-04-22T14:30:00+00:00', 'TRI 1126', 'Kawasaki', 'Curve 110', 2023, 'Orange', 'ENG00002358', 'CHS00003546', 4, 73),
  (79, 'driver243@mabini-sbtf.test', 'TODA-024', 'renewal', 'approved', '2025-04-21T09:00:00+00:00', '2025-04-25T14:30:00+00:00', 'TRI 1504', 'Yamaha', 'YBR 125', 2020, 'Black', 'ENG00009432', 'CHS00014184', 4, 77),
  (80, 'driver063@mabini-sbtf.test', 'TODA-006', 'renewal', 'approved', '2025-04-21T09:00:00+00:00', '2025-05-01T14:30:00+00:00', 'TRI 1126', 'Kawasaki', 'Curve 110', 2023, 'Orange', 'ENG00002358', 'CHS00003546', 4, 78),
  (81, 'driver123@mabini-sbtf.test', 'TODA-012', 'renewal', 'approved', '2025-04-21T09:00:00+00:00', '2025-04-25T14:30:00+00:00', 'TRI 1252', 'Rusi', 'Classic 250', 2022, 'Yellow', 'ENG00004716', 'CHS00007092', 4, 75),
  (82, 'driver022@mabini-sbtf.test', 'TODA-002', 'new', 'approved', '2025-05-02T09:00:00+00:00', '2025-05-03T14:30:00+00:00', 'TRI 1035', 'Honda', 'Wave 125', 2010, 'Green', 'ENG00000655', 'CHS00000985', 6, null),
  (83, 'driver082@mabini-sbtf.test', 'TODA-008', 'new', 'approved', '2025-05-02T09:00:00+00:00', '2025-05-09T14:30:00+00:00', 'TRI 1161', 'Suzuki', 'GD 110', 2009, 'White', 'ENG00003013', 'CHS00004531', 6, null),
  (84, 'driver142@mabini-sbtf.test', 'TODA-014', 'new', 'approved', '2025-05-02T09:00:00+00:00', '2025-05-03T14:30:00+00:00', 'TRI 1287', 'Kawasaki', 'Barako 175', 2008, 'Red', 'ENG00005371', 'CHS00008077', 6, null),
  (85, 'driver082@mabini-sbtf.test', 'TODA-008', 'renewal', 'approved', '2025-05-11T09:00:00+00:00', '2025-05-18T14:30:00+00:00', 'TRI 1161', 'Suzuki', 'GD 110', 2009, 'White', 'ENG00003013', 'CHS00004531', 6, 83),
  (86, 'driver142@mabini-sbtf.test', 'TODA-014', 'renewal', 'approved', '2025-05-11T09:00:00+00:00', '2025-05-12T14:30:00+00:00', 'TRI 1287', 'Kawasaki', 'Barako 175', 2008, 'Red', 'ENG00005371', 'CHS00008077', 6, 84),
  (87, 'driver202@mabini-sbtf.test', 'TODA-020', 'renewal', 'approved', '2025-05-11T09:00:00+00:00', '2025-05-18T14:30:00+00:00', 'TRI 1413', 'Honda', 'XRM 125', 2007, 'Gray', 'ENG00007729', 'CHS00011623', 6, 9),
  (88, 'driver142@mabini-sbtf.test', 'TODA-014', 'renewal', 'approved', '2025-05-20T09:00:00+00:00', '2025-05-21T14:30:00+00:00', 'TRI 1287', 'Kawasaki', 'Barako 175', 2008, 'Red', 'ENG00005371', 'CHS00008077', 6, 86),
  (89, 'driver022@mabini-sbtf.test', 'TODA-002', 'renewal', 'approved', '2025-05-20T09:00:00+00:00', '2025-05-21T14:30:00+00:00', 'TRI 1035', 'Honda', 'Wave 125', 2010, 'Green', 'ENG00000655', 'CHS00000985', 6, 82),
  (90, 'driver082@mabini-sbtf.test', 'TODA-008', 'renewal', 'approved', '2025-05-20T09:00:00+00:00', '2025-05-27T14:30:00+00:00', 'TRI 1161', 'Suzuki', 'GD 110', 2009, 'White', 'ENG00003013', 'CHS00004531', 6, 85),
  (91, 'driver161@mabini-sbtf.test', 'TODA-016', 'new', 'approved', '2025-06-01T09:00:00+00:00', '2025-06-11T14:30:00+00:00', 'TRI 1322', 'Rusi', 'Classic 250', 2013, 'Yellow', 'ENG00006026', 'CHS00009062', 5, null),
  (92, 'driver221@mabini-sbtf.test', 'TODA-022', 'new', 'approved', '2025-06-01T09:00:00+00:00', '2025-06-05T14:30:00+00:00', 'TRI 1448', 'Kawasaki', 'CT100', 2012, 'Silver', 'ENG00008384', 'CHS00012608', 5, null),
  (93, 'driver041@mabini-sbtf.test', 'TODA-004', 'new', 'approved', '2025-06-01T09:00:00+00:00', '2025-06-11T14:30:00+00:00', 'TRI 1070', 'Honda', 'TMX 155', 2015, 'Blue', 'ENG00001310', 'CHS00001970', 5, null),
  (94, 'driver221@mabini-sbtf.test', 'TODA-022', 'new', 'approved', '2025-06-10T09:00:00+00:00', '2025-06-14T14:30:00+00:00', 'TRI 1448', 'Kawasaki', 'CT100', 2012, 'Silver', 'ENG00008384', 'CHS00012608', 5, null),
  (95, 'driver101@mabini-sbtf.test', 'TODA-010', 'new', 'approved', '2025-06-10T09:00:00+00:00', '2025-06-14T14:30:00+00:00', 'TRI 1196', 'Kawasaki', 'Curve 110', 2014, 'Orange', 'ENG00003668', 'CHS00005516', 5, null),
  (96, 'driver161@mabini-sbtf.test', 'TODA-016', 'new', 'approved', '2025-06-10T09:00:00+00:00', '2025-06-20T14:30:00+00:00', 'TRI 1322', 'Rusi', 'Classic 250', 2013, 'Yellow', 'ENG00006026', 'CHS00009062', 5, null),
  (97, 'driver101@mabini-sbtf.test', 'TODA-010', 'new', 'approved', '2025-06-19T09:00:00+00:00', '2025-06-23T14:30:00+00:00', 'TRI 1196', 'Kawasaki', 'Curve 110', 2014, 'Orange', 'ENG00003668', 'CHS00005516', 5, null),
  (98, 'driver161@mabini-sbtf.test', 'TODA-016', 'new', 'approved', '2025-06-19T09:00:00+00:00', '2025-06-29T14:30:00+00:00', 'TRI 1322', 'Rusi', 'Classic 250', 2013, 'Yellow', 'ENG00006026', 'CHS00009062', 5, null),
  (99, 'driver221@mabini-sbtf.test', 'TODA-022', 'new', 'approved', '2025-06-19T09:00:00+00:00', '2025-06-23T14:30:00+00:00', 'TRI 1448', 'Kawasaki', 'CT100', 2012, 'Silver', 'ENG00008384', 'CHS00012608', 5, null),
  (100, 'driver173@mabini-sbtf.test', 'TODA-017', 'new', 'approved', '2025-07-09T09:00:00+00:00', '2025-07-16T14:30:00+00:00', 'TRI 1357', 'Kawasaki', 'Barako 175', 2018, 'Red', 'ENG00006681', 'CHS00010047', 4, null),
  (101, 'driver233@mabini-sbtf.test', 'TODA-023', 'new', 'approved', '2025-07-09T09:00:00+00:00', '2025-07-10T14:30:00+00:00', 'TRI 1483', 'Honda', 'XRM 125', 2017, 'Gray', 'ENG00009039', 'CHS00013593', 4, null),
  (102, 'driver053@mabini-sbtf.test', 'TODA-005', 'new', 'approved', '2025-07-09T09:00:00+00:00', '2025-07-16T14:30:00+00:00', 'TRI 1105', 'Honda', 'Wave 125', 2020, 'Green', 'ENG00001965', 'CHS00002955', 4, null),
  (103, 'driver233@mabini-sbtf.test', 'TODA-023', 'renewal', 'approved', '2025-07-18T09:00:00+00:00', '2025-07-19T14:30:00+00:00', 'TRI 1483', 'Honda', 'XRM 125', 2017, 'Gray', 'ENG00009039', 'CHS00013593', 4, 101),
  (104, 'driver053@mabini-sbtf.test', 'TODA-005', 'renewal', 'approved', '2025-07-18T09:00:00+00:00', '2025-07-25T14:30:00+00:00', 'TRI 1105', 'Honda', 'Wave 125', 2020, 'Green', 'ENG00001965', 'CHS00002955', 4, 102),
  (105, 'driver113@mabini-sbtf.test', 'TODA-011', 'new', 'approved', '2025-07-18T09:00:00+00:00', '2025-07-19T14:30:00+00:00', 'TRI 1231', 'Suzuki', 'GD 110', 2019, 'White', 'ENG00004323', 'CHS00006501', 4, null),
  (106, 'driver053@mabini-sbtf.test', 'TODA-005', 'renewal', 'approved', '2025-07-27T09:00:00+00:00', '2025-08-03T14:30:00+00:00', 'TRI 1105', 'Honda', 'Wave 125', 2020, 'Green', 'ENG00001965', 'CHS00002955', 4, 104),
  (107, 'driver113@mabini-sbtf.test', 'TODA-011', 'renewal', 'approved', '2025-07-27T09:00:00+00:00', '2025-07-28T14:30:00+00:00', 'TRI 1231', 'Suzuki', 'GD 110', 2019, 'White', 'ENG00004323', 'CHS00006501', 4, 105),
  (108, 'driver173@mabini-sbtf.test', 'TODA-017', 'renewal', 'approved', '2025-07-27T09:00:00+00:00', '2025-08-03T14:30:00+00:00', 'TRI 1357', 'Kawasaki', 'Barako 175', 2018, 'Red', 'ENG00006681', 'CHS00010047', 4, 100),
  (109, 'driver233@mabini-sbtf.test', 'TODA-023', 'renewal', 'approved', '2025-07-27T09:00:00+00:00', '2025-07-28T14:30:00+00:00', 'TRI 1483', 'Honda', 'XRM 125', 2017, 'Gray', 'ENG00009039', 'CHS00013593', 4, 103),
  (110, 'driver031@mabini-sbtf.test', 'TODA-003', 'new', 'pending', '2025-08-07T09:00:00+00:00', null, 'TRI 1049', 'Motorstar', 'Z200', 2012, 'Maroon', 'ENG00000917', 'CHS00001379', 5, null),
  (111, 'driver091@mabini-sbtf.test', 'TODA-009', 'new', 'pending', '2025-08-07T09:00:00+00:00', null, 'TRI 1175', 'Honda', 'Wave 125', 2011, 'Green', 'ENG00003275', 'CHS00004925', 5, null),
  (112, 'driver151@mabini-sbtf.test', 'TODA-015', 'new', 'pending', '2025-08-07T09:00:00+00:00', null, 'TRI 1301', 'Suzuki', 'GD 110', 2010, 'White', 'ENG00005633', 'CHS00008471', 5, null),
  (113, 'driver072@mabini-sbtf.test', 'TODA-007', 'new', 'rejected', '2025-08-08T09:00:00+00:00', '2025-08-12T14:30:00+00:00', 'TRI 1140', 'Honda', 'TMX 155', 2006, 'Blue', 'ENG00002620', 'CHS00003940', 6, null),
  (114, 'driver132@mabini-sbtf.test', 'TODA-013', 'new', 'rejected', '2025-08-08T09:00:00+00:00', '2025-08-18T14:30:00+00:00', 'TRI 1266', 'Kawasaki', 'Curve 110', 2005, 'Orange', 'ENG00004978', 'CHS00007486', 6, null),
  (115, 'driver192@mabini-sbtf.test', 'TODA-019', 'new', 'rejected', '2025-08-08T09:00:00+00:00', '2025-08-12T14:30:00+00:00', 'TRI 1392', 'Rusi', 'Classic 250', 2023, 'Yellow', 'ENG00007336', 'CHS00011032', 6, null),
  (116, 'driver012@mabini-sbtf.test', 'TODA-001', 'new', 'rejected', '2025-08-08T09:00:00+00:00', '2025-08-18T14:30:00+00:00', 'TRI 1014', 'Yamaha', 'YBR 125', 2007, 'Black', 'ENG00000262', 'CHS00000394', 6, null),
  (117, 'driver091@mabini-sbtf.test', 'TODA-009', 'new', 'pending', '2025-08-16T09:00:00+00:00', null, 'TRI 1175', 'Honda', 'Wave 125', 2011, 'Green', 'ENG00003275', 'CHS00004925', 5, null),
  (118, 'driver151@mabini-sbtf.test', 'TODA-015', 'new', 'pending', '2025-08-16T09:00:00+00:00', null, 'TRI 1301', 'Suzuki', 'GD 110', 2010, 'White', 'ENG00005633', 'CHS00008471', 5, null),
  (119, 'driver211@mabini-sbtf.test', 'TODA-021', 'new', 'pending', '2025-08-16T09:00:00+00:00', null, 'TRI 1427', 'Kawasaki', 'Barako 175', 2009, 'Red', 'ENG00007991', 'CHS00012017', 5, null),
  (120, 'driver192@mabini-sbtf.test', 'TODA-019', 'new', 'rejected', '2025-08-17T09:00:00+00:00', '2025-08-21T14:30:00+00:00', 'TRI 1392', 'Rusi', 'Classic 250', 2023, 'Yellow', 'ENG00007336', 'CHS00011032', 6, null),
  (121, 'driver012@mabini-sbtf.test', 'TODA-001', 'new', 'rejected', '2025-08-17T09:00:00+00:00', '2025-08-27T14:30:00+00:00', 'TRI 1014', 'Yamaha', 'YBR 125', 2007, 'Black', 'ENG00000262', 'CHS00000394', 6, null),
  (122, 'driver072@mabini-sbtf.test', 'TODA-007', 'new', 'rejected', '2025-08-17T09:00:00+00:00', '2025-08-21T14:30:00+00:00', 'TRI 1140', 'Honda', 'TMX 155', 2006, 'Blue', 'ENG00002620', 'CHS00003940', 6, null),
  (123, 'driver151@mabini-sbtf.test', 'TODA-015', 'new', 'pending', '2025-08-25T09:00:00+00:00', null, 'TRI 1301', 'Suzuki', 'GD 110', 2010, 'White', 'ENG00005633', 'CHS00008471', 5, null),
  (124, 'driver211@mabini-sbtf.test', 'TODA-021', 'new', 'pending', '2025-08-25T09:00:00+00:00', null, 'TRI 1427', 'Kawasaki', 'Barako 175', 2009, 'Red', 'ENG00007991', 'CHS00012017', 5, null),
  (125, 'driver031@mabini-sbtf.test', 'TODA-003', 'new', 'pending', '2025-08-25T09:00:00+00:00', null, 'TRI 1049', 'Motorstar', 'Z200', 2012, 'Maroon', 'ENG00000917', 'CHS00001379', 5, null),
  (126, 'driver091@mabini-sbtf.test', 'TODA-009', 'new', 'pending', '2025-08-25T09:00:00+00:00', null, 'TRI 1175', 'Honda', 'Wave 125', 2011, 'Green', 'ENG00003275', 'CHS00004925', 5, null),
  (127, 'driver012@mabini-sbtf.test', 'TODA-001', 'new', 'rejected', '2025-08-26T09:00:00+00:00', '2025-09-05T14:30:00+00:00', 'TRI 1014', 'Yamaha', 'YBR 125', 2007, 'Black', 'ENG00000262', 'CHS00000394', 6, null),
  (128, 'driver072@mabini-sbtf.test', 'TODA-007', 'new', 'rejected', '2025-08-26T09:00:00+00:00', '2025-08-30T14:30:00+00:00', 'TRI 1140', 'Honda', 'TMX 155', 2006, 'Blue', 'ENG00002620', 'CHS00003940', 6, null),
  (129, 'driver132@mabini-sbtf.test', 'TODA-013', 'new', 'rejected', '2025-08-26T09:00:00+00:00', '2025-09-05T14:30:00+00:00', 'TRI 1266', 'Kawasaki', 'Curve 110', 2005, 'Orange', 'ENG00004978', 'CHS00007486', 6, null),
  (130, 'driver163@mabini-sbtf.test', 'TODA-016', 'new', 'approved', '2025-09-06T09:00:00+00:00', '2025-09-10T14:30:00+00:00', 'TRI 1336', 'Kawasaki', 'Curve 110', 2015, 'Orange', 'ENG00006288', 'CHS00009456', 4, null),
  (131, 'driver223@mabini-sbtf.test', 'TODA-022', 'new', 'approved', '2025-09-06T09:00:00+00:00', '2025-09-16T14:30:00+00:00', 'TRI 1462', 'Rusi', 'Classic 250', 2014, 'Yellow', 'ENG00008646', 'CHS00013002', 4, null),
  (132, 'driver043@mabini-sbtf.test', 'TODA-004', 'new', 'approved', '2025-09-06T09:00:00+00:00', '2025-09-10T14:30:00+00:00', 'TRI 1084', 'Yamaha', 'YBR 125', 2017, 'Black', 'ENG00001572', 'CHS00002364', 4, null),
  (133, 'driver103@mabini-sbtf.test', 'TODA-010', 'new', 'approved', '2025-09-06T09:00:00+00:00', '2025-09-16T14:30:00+00:00', 'TRI 1210', 'Honda', 'TMX 155', 2016, 'Blue', 'ENG00003930', 'CHS00005910', 4, null),
  (134, 'driver043@mabini-sbtf.test', 'TODA-004', 'renewal', 'approved', '2025-09-15T09:00:00+00:00', '2025-09-19T14:30:00+00:00', 'TRI 1084', 'Yamaha', 'YBR 125', 2017, 'Black', 'ENG00001572', 'CHS00002364', 4, 132),
  (135, 'driver103@mabini-sbtf.test', 'TODA-010', 'renewal', 'approved', '2025-09-15T09:00:00+00:00', '2025-09-25T14:30:00+00:00', 'TRI 1210', 'Honda', 'TMX 155', 2016, 'Blue', 'ENG00003930', 'CHS00005910', 4, 133),
  (136, 'driver163@mabini-sbtf.test', 'TODA-016', 'renewal', 'approved', '2025-09-15T09:00:00+00:00', '2025-09-19T14:30:00+00:00', 'TRI 1336', 'Kawasaki', 'Curve 110', 2015, 'Orange', 'ENG00006288', 'CHS00009456', 4, 130),
  (137, 'driver103@mabini-sbtf.test', 'TODA-010', 'renewal', 'approved', '2025-09-24T09:00:00+00:00', '2025-10-04T14:30:00+00:00', 'TRI 1210', 'Honda', 'TMX 155', 2016, 'Blue', 'ENG00003930', 'CHS00005910', 4, 135),
  (138, 'driver163@mabini-sbtf.test', 'TODA-016', 'renewal', 'approved', '2025-09-24T09:00:00+00:00', '2025-09-28T14:30:00+00:00', 'TRI 1336', 'Kawasaki', 'Curve 110', 2015, 'Orange', 'ENG00006288', 'CHS00009456', 4, 136),
  (139, 'driver223@mabini-sbtf.test', 'TODA-022', 'renewal', 'approved', '2025-09-24T09:00:00+00:00', '2025-10-04T14:30:00+00:00', 'TRI 1462', 'Rusi', 'Classic 250', 2014, 'Yellow', 'ENG00008646', 'CHS00013002', 4, 131),
  (140, 'driver122@mabini-sbtf.test', 'TODA-012', 'new', 'approved', '2025-10-05T09:00:00+00:00', '2025-10-12T14:30:00+00:00', 'TRI 1245', 'Honda', 'Wave 125', 2021, 'Green', 'ENG00004585', 'CHS00006895', 6, null),
  (141, 'driver182@mabini-sbtf.test', 'TODA-018', 'new', 'approved', '2025-10-05T09:00:00+00:00', '2025-10-06T14:30:00+00:00', 'TRI 1371', 'Suzuki', 'GD 110', 2020, 'White', 'ENG00006943', 'CHS00010441', 6, null),
  (142, 'driver242@mabini-sbtf.test', 'TODA-024', 'new', 'approved', '2025-10-05T09:00:00+00:00', '2025-10-12T14:30:00+00:00', 'TRI 1497', 'Kawasaki', 'Barako 175', 2019, 'Red', 'ENG00009301', 'CHS00013987', 6, null),
  (143, 'driver182@mabini-sbtf.test', 'TODA-018', 'renewal', 'approved', '2025-10-14T09:00:00+00:00', '2025-10-15T14:30:00+00:00', 'TRI 1371', 'Suzuki', 'GD 110', 2020, 'White', 'ENG00006943', 'CHS00010441', 6, 141),
  (144, 'driver242@mabini-sbtf.test', 'TODA-024', 'renewal', 'approved', '2025-10-14T09:00:00+00:00', '2025-10-21T14:30:00+00:00', 'TRI 1497', 'Kawasaki', 'Barako 175', 2019, 'Red', 'ENG00009301', 'CHS00013987', 6, 142),
  (145, 'driver062@mabini-sbtf.test', 'TODA-006', 'new', 'approved', '2025-10-14T09:00:00+00:00', '2025-10-15T14:30:00+00:00', 'TRI 1119', 'Motorstar', 'Z200', 2022, 'Maroon', 'ENG00002227', 'CHS00003349', 6, null),
  (146, 'driver242@mabini-sbtf.test', 'TODA-024', 'renewal', 'approved', '2025-10-23T09:00:00+00:00', '2025-10-30T14:30:00+00:00', 'TRI 1497', 'Kawasaki', 'Barako 175', 2019, 'Red', 'ENG00009301', 'CHS00013987', 6, 144),
  (147, 'driver062@mabini-sbtf.test', 'TODA-006', 'renewal', 'approved', '2025-10-23T09:00:00+00:00', '2025-10-24T14:30:00+00:00', 'TRI 1119', 'Motorstar', 'Z200', 2022, 'Maroon', 'ENG00002227', 'CHS00003349', 6, 145),
  (148, 'driver122@mabini-sbtf.test', 'TODA-012', 'renewal', 'approved', '2025-10-23T09:00:00+00:00', '2025-10-30T14:30:00+00:00', 'TRI 1245', 'Honda', 'Wave 125', 2021, 'Green', 'ENG00004585', 'CHS00006895', 6, 140),
  (149, 'driver182@mabini-sbtf.test', 'TODA-018', 'renewal', 'approved', '2025-10-23T09:00:00+00:00', '2025-10-24T14:30:00+00:00', 'TRI 1371', 'Suzuki', 'GD 110', 2020, 'White', 'ENG00006943', 'CHS00010441', 6, 143),
  (150, 'driver213@mabini-sbtf.test', 'TODA-021', 'new', 'approved', '2025-11-03T09:00:00+00:00', '2025-11-10T14:30:00+00:00', 'TRI 1441', 'Suzuki', 'GD 110', 2011, 'White', 'ENG00008253', 'CHS00012411', 4, null),
  (151, 'driver033@mabini-sbtf.test', 'TODA-003', 'new', 'approved', '2025-11-03T09:00:00+00:00', '2025-11-04T14:30:00+00:00', 'TRI 1063', 'Honda', 'XRM 125', 2014, 'Gray', 'ENG00001179', 'CHS00001773', 4, null),
  (152, 'driver093@mabini-sbtf.test', 'TODA-009', 'new', 'approved', '2025-11-03T09:00:00+00:00', '2025-11-10T14:30:00+00:00', 'TRI 1189', 'Motorstar', 'Z200', 2013, 'Maroon', 'ENG00003537', 'CHS00005319', 4, null),
  (153, 'driver021@mabini-sbtf.test', 'TODA-002', 'new', 'approved', '2025-11-04T09:00:00+00:00', '2025-11-08T14:30:00+00:00', 'TRI 1028', 'Kawasaki', 'CT100', 2009, 'Silver', 'ENG00000524', 'CHS00000788', 5, null),
  (154, 'driver081@mabini-sbtf.test', 'TODA-008', 'new', 'approved', '2025-11-04T09:00:00+00:00', '2025-11-14T14:30:00+00:00', 'TRI 1154', 'Yamaha', 'YBR 125', 2008, 'Black', 'ENG00002882', 'CHS00004334', 5, null),
  (155, 'driver141@mabini-sbtf.test', 'TODA-014', 'new', 'approved', '2025-11-04T09:00:00+00:00', '2025-11-08T14:30:00+00:00', 'TRI 1280', 'Honda', 'TMX 155', 2007, 'Blue', 'ENG00005240', 'CHS00007880', 5, null),
  (156, 'driver033@mabini-sbtf.test', 'TODA-003', 'renewal', 'approved', '2025-11-12T09:00:00+00:00', '2025-11-13T14:30:00+00:00', 'TRI 1063', 'Honda', 'XRM 125', 2014, 'Gray', 'ENG00001179', 'CHS00001773', 4, 151),
  (157, 'driver093@mabini-sbtf.test', 'TODA-009', 'renewal', 'approved', '2025-11-12T09:00:00+00:00', '2025-11-19T14:30:00+00:00', 'TRI 1189', 'Motorstar', 'Z200', 2013, 'Maroon', 'ENG00003537', 'CHS00005319', 4, 152),
  (158, 'driver153@mabini-sbtf.test', 'TODA-015', 'new', 'approved', '2025-11-12T09:00:00+00:00', '2025-11-13T14:30:00+00:00', 'TRI 1315', 'Honda', 'Wave 125', 2012, 'Green', 'ENG00005895', 'CHS00008865', 4, null),
  (159, 'driver081@mabini-sbtf.test', 'TODA-008', 'new', 'approved', '2025-11-13T09:00:00+00:00', '2025-11-23T14:30:00+00:00', 'TRI 1154', 'Yamaha', 'YBR 125', 2008, 'Black', 'ENG00002882', 'CHS00004334', 5, null),
  (160, 'driver141@mabini-sbtf.test', 'TODA-014', 'new', 'approved', '2025-11-13T09:00:00+00:00', '2025-11-17T14:30:00+00:00', 'TRI 1280', 'Honda', 'TMX 155', 2007, 'Blue', 'ENG00005240', 'CHS00007880', 5, null),
  (161, 'driver201@mabini-sbtf.test', 'TODA-020', 'new', 'approved', '2025-11-13T09:00:00+00:00', '2025-11-23T14:30:00+00:00', 'TRI 1406', 'Kawasaki', 'Curve 110', 2006, 'Orange', 'ENG00007598', 'CHS00011426', 5, null),
  (162, 'driver021@mabini-sbtf.test', 'TODA-002', 'new', 'approved', '2025-11-13T09:00:00+00:00', '2025-11-17T14:30:00+00:00', 'TRI 1028', 'Kawasaki', 'CT100', 2009, 'Silver', 'ENG00000524', 'CHS00000788', 5, null),
  (163, 'driver093@mabini-sbtf.test', 'TODA-009', 'renewal', 'approved', '2025-11-21T09:00:00+00:00', '2025-11-28T14:30:00+00:00', 'TRI 1189', 'Motorstar', 'Z200', 2013, 'Maroon', 'ENG00003537', 'CHS00005319', 4, 157),
  (164, 'driver153@mabini-sbtf.test', 'TODA-015', 'renewal', 'approved', '2025-11-21T09:00:00+00:00', '2025-11-22T14:30:00+00:00', 'TRI 1315', 'Honda', 'Wave 125', 2012, 'Green', 'ENG00005895', 'CHS00008865', 4, 158),
  (165, 'driver213@mabini-sbtf.test', 'TODA-021', 'renewal', 'approved', '2025-11-21T09:00:00+00:00', '2025-11-28T14:30:00+00:00', 'TRI 1441', 'Suzuki', 'GD 110', 2011, 'White', 'ENG00008253', 'CHS00012411', 4, 150),
  (166, 'driver033@mabini-sbtf.test', 'TODA-003', 'renewal', 'approved', '2025-11-21T09:00:00+00:00', '2025-11-22T14:30:00+00:00', 'TRI 1063', 'Honda', 'XRM 125', 2014, 'Gray', 'ENG00001179', 'CHS00001773', 4, 156),
  (167, 'driver201@mabini-sbtf.test', 'TODA-020', 'new', 'approved', '2025-11-22T09:00:00+00:00', '2025-12-02T14:30:00+00:00', 'TRI 1406', 'Kawasaki', 'Curve 110', 2006, 'Orange', 'ENG00007598', 'CHS00011426', 5, null),
  (168, 'driver021@mabini-sbtf.test', 'TODA-002', 'new', 'approved', '2025-11-22T09:00:00+00:00', '2025-11-26T14:30:00+00:00', 'TRI 1028', 'Kawasaki', 'CT100', 2009, 'Silver', 'ENG00000524', 'CHS00000788', 5, null),
  (169, 'driver081@mabini-sbtf.test', 'TODA-008', 'new', 'approved', '2025-11-22T09:00:00+00:00', '2025-12-02T14:30:00+00:00', 'TRI 1154', 'Yamaha', 'YBR 125', 2008, 'Black', 'ENG00002882', 'CHS00004334', 5, null),
  (170, 'driver112@mabini-sbtf.test', 'TODA-011', 'new', 'approved', '2025-12-02T09:00:00+00:00', '2025-12-06T14:30:00+00:00', 'TRI 1224', 'Yamaha', 'YBR 125', 2018, 'Black', 'ENG00004192', 'CHS00006304', 6, null),
  (171, 'driver172@mabini-sbtf.test', 'TODA-017', 'new', 'approved', '2025-12-02T09:00:00+00:00', '2025-12-12T14:30:00+00:00', 'TRI 1350', 'Honda', 'TMX 155', 2017, 'Blue', 'ENG00006550', 'CHS00009850', 6, null),
  (172, 'driver232@mabini-sbtf.test', 'TODA-023', 'new', 'approved', '2025-12-02T09:00:00+00:00', '2025-12-06T14:30:00+00:00', 'TRI 1476', 'Kawasaki', 'Curve 110', 2016, 'Orange', 'ENG00008908', 'CHS00013396', 6, null),
  (173, 'driver172@mabini-sbtf.test', 'TODA-017', 'renewal', 'pending', '2025-12-11T09:00:00+00:00', null, 'TRI 1350', 'Honda', 'TMX 155', 2017, 'Blue', 'ENG00006550', 'CHS00009850', 6, 171),
  (174, 'driver232@mabini-sbtf.test', 'TODA-023', 'renewal', 'pending', '2025-12-11T09:00:00+00:00', null, 'TRI 1476', 'Kawasaki', 'Curve 110', 2016, 'Orange', 'ENG00008908', 'CHS00013396', 6, 172),
  (175, 'driver052@mabini-sbtf.test', 'TODA-005', 'new', 'pending', '2025-12-11T09:00:00+00:00', null, 'TRI 1098', 'Kawasaki', 'CT100', 2019, 'Silver', 'ENG00001834', 'CHS00002758', 6, null),
  (176, 'driver112@mabini-sbtf.test', 'TODA-011', 'renewal', 'pending', '2025-12-11T09:00:00+00:00', null, 'TRI 1224', 'Yamaha', 'YBR 125', 2018, 'Black', 'ENG00004192', 'CHS00006304', 6, 170),
  (177, 'driver052@mabini-sbtf.test', 'TODA-005', 'new', 'pending', '2025-12-20T09:00:00+00:00', null, 'TRI 1098', 'Kawasaki', 'CT100', 2019, 'Silver', 'ENG00001834', 'CHS00002758', 6, null),
  (178, 'driver112@mabini-sbtf.test', 'TODA-011', 'new', 'pending', '2025-12-20T09:00:00+00:00', null, 'TRI 1224', 'Yamaha', 'YBR 125', 2018, 'Black', 'ENG00004192', 'CHS00006304', 6, null),
  (179, 'driver172@mabini-sbtf.test', 'TODA-017', 'new', 'pending', '2025-12-20T09:00:00+00:00', null, 'TRI 1350', 'Honda', 'TMX 155', 2017, 'Blue', 'ENG00006550', 'CHS00009850', 6, null);

do $$
declare
  r              record;
  v_app_id       uuid;
  v_record_id    uuid;
  v_app_number   text;
  v_fr_number    text;
  v_year         integer;
  v_app_seq      integer;
  v_fr_seq       integer;
  v_verified_at  timestamptz;
  v_actor        uuid;
  v_doc          public.document_type;
  v_reason       text;
  v_predecessor  uuid;
begin
  create temporary table if not exists seed_counters (
    calendar_year integer primary key,
    app_counter   integer not null default 0,
    fr_counter    integer not null default 0
  ) on commit drop;

  create temporary table if not exists seed_ids (
    ordinal   integer primary key,
    app_id    uuid not null
  ) on commit drop;

  for r in select * from seed_apps order by submitted_at, ordinal
  loop
    v_year := extract(year from r.submitted_at)::integer;

    insert into seed_counters (calendar_year) values (v_year)
    on conflict (calendar_year) do nothing;

    update seed_counters set app_counter = app_counter + 1
     where calendar_year = v_year
    returning app_counter into v_app_seq;

    v_app_number := 'APP-' || v_year || '-' || lpad(v_app_seq::text, 6, '0');

    select id into v_actor
      from public.profiles
     where lower(email) = lower(r.driver_email);

    v_predecessor := null;
    if r.predecessor_seq is not null then
      select fr.id into v_predecessor
        from public.franchise_records fr
        join seed_ids si on si.app_id = fr.application_id
       where si.ordinal = r.predecessor_seq;
    end if;

    insert into public.franchise_applications (
      application_number, applicant_id, application_type, status, toda_id,
      renewal_of_record_id,
      operator_first_name, operator_middle_name, operator_last_name,
      operator_contact_number, operator_address_line, operator_barangay_code, operator_email,
      vehicle_make, vehicle_model, vehicle_year, vehicle_color,
      plate_number, engine_number, chassis_number, seating_capacity,
      submitted_at, created_at
    )
    select
      v_app_number, p.id, r.application_type, 'pending', t.id,
      v_predecessor,
      p.first_name, p.middle_name, p.last_name,
      coalesce(p.contact_number, '09180000000'),
      coalesce(p.address_line, 'Purok 1') || ', ' || t.name,
      p.barangay_code, p.email,
      r.vehicle_make, r.vehicle_model, r.vehicle_year, r.vehicle_color,
      r.plate_number, r.engine_number, r.chassis_number, r.seating_capacity,
      r.submitted_at, r.submitted_at
      from public.profiles p
      join public.todas t on t.code = r.toda_code
     where p.id = v_actor
    returning id into v_app_id;

    insert into seed_ids (ordinal, app_id) values (r.ordinal, v_app_id);

    -- The four documentary requirements
    for v_doc in
      select * from unnest(enum_range(null::public.document_type)) as dt(document_type)
    loop
      insert into public.franchise_documents (
        application_id, document_type, storage_path, file_name, file_size_bytes, mime_type,
        uploaded_at
      )
      values (
        v_app_id, v_doc,
        v_actor::text || '/' || v_app_id::text || '/' || v_doc::text || '-' ||
          extract(epoch from r.submitted_at)::bigint || '.pdf',
        v_doc::text || '.pdf',
        180000 + (r.ordinal * 977) % 400000,
        'application/pdf',
        r.submitted_at
      );
    end loop;

    if r.status <> 'pending' then
      -- Verification staff process the documents before deciding.
      select id into v_actor
        from public.profiles
       where role in ('staff', 'administrator')
       order by email
       limit 1 offset (r.ordinal % 4);

      v_verified_at := r.reviewed_at - interval '1 day';

      update public.franchise_documents
         set verification_status = 'verified',
             verified_by = v_actor,
             verified_at = v_verified_at
       where application_id = v_app_id
         and verification_status = 'pending';

      if r.status = 'approved' then
        update seed_counters set fr_counter = fr_counter + 1
         where calendar_year = v_year
        returning fr_counter into v_fr_seq;

        v_fr_number := 'MAB-TR-' || v_year || '-' || lpad(v_fr_seq::text, 6, '0');

        insert into public.franchise_records (
          application_id, operator_id, toda_id, franchise_number, verification_code,
          issued_at, expires_at, created_at
        )
        select a.id,
               a.applicant_id,
               a.toda_id,
               v_fr_number,
               public.fn_generate_verification_code(),
               r.reviewed_at,
               r.reviewed_at + make_interval(months => 12),
               r.reviewed_at
          from public.franchise_applications a
         where a.id = v_app_id
        returning id into v_record_id;

        -- Final status transition: fires exactly the same audit and notification
        -- triggers that the staff approval function fires in production.
        update public.franchise_applications
           set status = 'approved',
               reviewed_by = v_actor,
               reviewed_at = r.reviewed_at,
               review_started_at = r.reviewed_at - interval '1 day',
               review_started_by = v_actor
         where id = v_app_id;

        -- Forward link on the predecessor: "this franchise was renewed by …".
        -- No other column of the predecessor is touched.
        if v_predecessor is not null then
          update public.franchise_records
             set renewed_by_record_id = v_record_id
           where id = v_predecessor
             and renewed_by_record_id is null;
        end if;

      else
        v_reason := (array[
          'Barangay clearance presented has already expired; please submit a clearance issued within the current year.',
          'Photocopy of the Certificate of Registration is not legible; a clear copy or scanned original is required.',
          'Registered vehicle owner differs from the declared operator; please submit a deed of sale or authority to operate.',
          'Cedula presented belongs to a different individual; please upload the operator''s own cedula.',
          'Chassis number declared in the application does not match the OR/CR on file; please verify and re-submit.'
        ])[(r.ordinal % 5) + 1];

        update public.franchise_applications
           set status = 'rejected',
               rejection_reason = v_reason,
               reviewed_by = v_actor,
               reviewed_at = r.reviewed_at
         where id = v_app_id;
      end if;
    end if;
  end loop;

  -- Align the production counters with the seeded data so that live submissions
  -- continue the numbering without collisions. franchise_number_sequences is
  -- keyed by calendar year and holds one column per series.
  insert into public.franchise_number_sequences (
    calendar_year, last_value, last_application_value
  )
  select s.yr, s.fr_max, s.app_max
    from (
      select coalesce(fr.yr, ap.yr) as yr,
             coalesce(fr.fr_max, 0) as fr_max,
             coalesce(ap.app_max, 0) as app_max
        from (
          select extract(year from r.issued_at)::integer as yr,
                 max(substring(r.franchise_number from '([0-9]+)$')::integer) as fr_max
            from public.franchise_records r
           group by 1
        ) fr
        full join (
          select extract(year from a.submitted_at)::integer as yr,
                 max(substring(a.application_number from '([0-9]+)$')::integer) as app_max
            from public.franchise_applications a
           group by 1
        ) ap on ap.yr = fr.yr
    ) s
  on conflict (calendar_year) do update
    set last_value = greatest(public.franchise_number_sequences.last_value, excluded.last_value),
        last_application_value = greatest(
          public.franchise_number_sequences.last_application_value,
          excluded.last_application_value
        ),
        updated_at = now();
end
$$;

-- ---------------------------------------------------------------------------
-- 5. Verification codes for manual QR testing (development aid)
--    Run:  select franchise_number, verification_code from public.franchise_records limit 5;
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 6. Housekeeping: the seeding helper is not part of the deployed schema.
-- ---------------------------------------------------------------------------
drop function if exists public.seed_create_auth_user(text, text, public.user_role, text, text, text, text, text, text, timestamptz);

commit;

-- Reminder: demonstration credentials are listed in docs/deployment.md and
-- must never be used in a live deployment.
