import { NotificationList } from "@/components/notifications/notification-list";
import { Card, CardHeader, SectionTitle } from "@/components/ui";
import { listNotifications } from "@/lib/data";

export async function NotificationsPage({ basePath }: { basePath: "/admin" | "/staff" }) {
  const notifications = await listNotifications(50);

  return (
    <div>
      <SectionTitle
        title="Notifications"
        description="Delivered through the notifications table and pushed to the open console over Supabase Realtime."
      />
      <NotificationList notifications={notifications} basePath={basePath} />

      <Card className="mt-4">
        <CardHeader
          title="How notifications are produced"
          description="Notifications are written by database triggers and by the workflow functions — never by the browser — so the record of what was communicated cannot be forged from a client."
        />
        <ul className="space-y-2 text-[0.8125rem] text-muted">
          <li>Submission, review start, document verification and decisions notify the applicant.</li>
          <li>New submissions notify the staff and the administrators so the queue is never silently full.</li>
          <li>Renewal reminders at 90, 60 and 30 days are generated by a scheduled job; each reminder is recorded once per franchise and period.</li>
          <li>Account and role changes notify the affected user, and the change itself is written to the activity log.</li>
        </ul>
      </Card>
    </div>
  );
}
